version: "3.9"
services:
  api:
    build: .
    image: product-rag-api:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on: []
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped


